version: 2.1

jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:20-git
        environment:
          GCLOUD_SERVICE_KEY: $GCLOUD_SERVICE_KEY
          GOOGLE_PROJECT_ID: $GOOGLE_PROJECT_ID
          GOOGLE_COMPUTE_ZONE: $GOOGLE_COMPUTE_ZONE
          GOOGLE_REGISTRY_URL: $GOOGLE_REGISTRY_URL
          GOOGLE_CLOUD_SDK_VERSION: 379.0.0
          GCR_DOCKER_CREDENTIAL: 2.1.0
          DEPLOYMENT_NAMESPACE: $DEPLOYMENT_NAMESPACE
          DEPLOYMENT_NAME: $DEPLOYMENT_NAME
          SLACK_CHANNEL: $SLACK_CHANNEL
          SLACK_OAUTH: $SLACK_OAUTH
          CIRCLE_BRANCH: $CIRCLE_BRANCH
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add bash curl python3 py3-pip jq wget

            mkdir -p /usr/local/gcloud
            cd /usr/local/gcloud

            curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-$GOOGLE_CLOUD_SDK_VERSION-linux-x86_64.tar.gz
            tar -xf ./google-cloud-sdk-$GOOGLE_CLOUD_SDK_VERSION-linux-x86_64.tar.gz

            ./google-cloud-sdk/install.sh --quiet

            wget "https://github.com/GoogleCloudPlatform/docker-credential-gcr/releases/download/v$GCR_DOCKER_CREDENTIAL/docker-credential-gcr_linux_amd64-$GCR_DOCKER_CREDENTIAL.tar.gz" -O ./docker-credential-gcr_linux_amd64-$GCR_DOCKER_CREDENTIAL.tar.gz
            tar -xf ./docker-credential-gcr_linux_amd64-$GCR_DOCKER_CREDENTIAL.tar.gz

            mv ./docker-credential-gcr /usr/local/gcloud/google-cloud-sdk/bin/docker-credential-gcr

            PATH="$PATH:/usr/local/gcloud/google-cloud-sdk/bin"

            gcloud --quiet components update

            cd /app
      - run:
          name: Notify Slack about build
          command: |
            curl -d "text=Runeguard docs build has BEGUN DOCKER IMAGE BUILD on branch \`$CIRCLE_BRANCH\`." -d "channel=$SLACK_CHANNEL" -H "Authorization: Bearer $SLACK_OAUTH" -X POST https://slack.com/api/chat.postMessage
      - run:
          name: Build Docker Image
          command: |
            ./build.sh
      - deploy:
          name: Push application Docker image
          command: |
            PATH="$PATH:/usr/local/gcloud/google-cloud-sdk/bin"

            export GOOGLE_APPLICATION_CREDENTIALS="$GCLOUD_SERVICE_KEY"

            docker-credential-gcr configure-docker --registries=$GOOGLE_REGISTRY_URL,gcr.io

            echo "${GCLOUD_SERVICE_KEY}" | docker login -u _json_key --password-stdin https://$GOOGLE_REGISTRY_URL

            ./push.sh
      - run:
          name: Notify Slack about build
          command: |
            curl -d "text=Runeguard docs build has COMPLETED on branch \`$CIRCLE_BRANCH\`." -d "channel=$SLACK_CHANNEL" -H "Authorization: Bearer $SLACK_OAUTH" -X POST https://slack.com/api/chat.postMessage

workflows:
  version: 2
  runeguard-docs:
    jobs:
      - build: 
          filters:
            branches:
              only: 
                - master
